---
# roles/ansible_role_neofetch/tasks/main.yml

- name: Install neofetch
  ansible.builtin.apt:
    name: neofetch
    update_cache: true

- name: Deploy neofetch login script from role files
  ansible.builtin.copy:
    src: neofetch.sh
    dest: "/etc/profile.d/neofetch.sh"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
